// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "sources": string;
      "searchYears": number;
      "maxResults": number;
      "useTranslators": boolean;
      "hideExisting": boolean;
      "contactEmail": string;
      "timeoutSeconds": number;
      "prefsSchemaVersion": number;
      "logLevel": string;
      "logRequestBodies": boolean;
      "ncbi.keyPresent": boolean;
      "secretBackend": string;
    };
  }
}
